# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddependent.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QTableWidgetItem
import mysql.connector
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator


class Ui_AddDependent():
    passedssn = -1
    def __init__(self, obj):
        self.passedssn = obj.textEdit.text()

    def setupUi(self, AddDependent):
        AddDependent.setObjectName("AddDependent")
        AddDependent.resize(710, 622)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddDependent)
        self.buttonBox.setGeometry(QtCore.QRect(330, 510, 321, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(AddDependent)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 80, 641, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabdependents = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabdependents.sizePolicy().hasHeightForWidth())
        self.tabdependents.setSizePolicy(sizePolicy)
        self.tabdependents.setMinimumSize(QtCore.QSize(639, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabdependents.setFont(font)
        self.tabdependents.setAutoFillBackground(True)
        self.tabdependents.setGridStyle(QtCore.Qt.SolidLine)
        self.tabdependents.setRowCount(10)
        self.tabdependents.setColumnCount(4)
        self.tabdependents.setObjectName("tabdependents")
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(3, item)
        self.tabdependents.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tabdependents)
        self.label_2 = QtWidgets.QLabel(AddDependent)
        self.label_2.setGeometry(QtCore.QRect(30, 360, 55, 16))
        self.label_2.setObjectName("label_2")
        self.sex = QtWidgets.QComboBox(AddDependent)
        self.sex.setGeometry(QtCore.QRect(590, 350, 51, 31))
        self.sex.setObjectName("comboBox")
        self.sex.setCurrentText("")
        self.sex.addItem("M")
        self.sex.addItem("F")
        self.sex.setMaxCount(2)
        self.empssn = QtWidgets.QLineEdit(AddDependent)
        self.empssn.setGeometry(QtCore.QRect(90, 20, 101, 31))
        self.empssn.setObjectName("empssn")
        self.gobutton = QtWidgets.QPushButton(AddDependent)
        self.gobutton.setGeometry(QtCore.QRect(60, 510, 93, 28))
        self.gobutton.setObjectName("gobutton")
        self.label_5 = QtWidgets.QLabel(AddDependent)
        self.label_5.setGeometry(QtCore.QRect(300, 430, 91, 16))
        self.label_5.setObjectName("label_5")
        self.dateofbirth = QtWidgets.QDateEdit(AddDependent)
        self.dateofbirth.setGeometry(QtCore.QRect(120, 431, 110, 21))
        self.dateofbirth.setObjectName("dateofbirth")
        self.label_4 = QtWidgets.QLabel(AddDependent)
        self.label_4.setGeometry(QtCore.QRect(30, 430, 91, 16))
        self.label_4.setObjectName("label_4")
        self.dname = QtWidgets.QTextEdit(AddDependent)
        self.dname.setGeometry(QtCore.QRect(120, 350, 271, 31))
        self.dname.setObjectName("dname")
        self.label_3 = QtWidgets.QLabel(AddDependent)
        self.label_3.setGeometry(QtCore.QRect(520, 360, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(AddDependent)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.label.setObjectName("label")
        self.relationship = QtWidgets.QTextEdit(AddDependent)
        self.relationship.setGeometry(QtCore.QRect(380, 420, 261, 31))
        self.relationship.setObjectName("relationship")
        self.empname = QtWidgets.QLabel(AddDependent)
        self.empname.setGeometry(QtCore.QRect(240, 20, 71, 21))
        self.empname.setObjectName("empname")
        self.empname_2 = QtWidgets.QTextEdit(AddDependent)
        self.empname_2.setGeometry(QtCore.QRect(310, 20, 261, 31))
        self.empname_2.setObjectName("empname_2")
        self.label_6 = QtWidgets.QLabel(AddDependent)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 121, 16))
        self.label_6.setObjectName("label_6")
        self.depcount = QtWidgets.QTextEdit(AddDependent)
        self.depcount.setGeometry(QtCore.QRect(210, 300, 31, 31))
        self.depcount.setObjectName("depcount")

        self.empssn.setText(self.passedssn)
        self.empssn.setDisabled(True)
        self.retranslateUi(AddDependent)
        
        self.buttonBox.rejected.connect(AddDependent.reject)
        
        QtCore.QMetaObject.connectSlotsByName(AddDependent)

        self.gobutton.clicked.connect(self.processinsert)

        self.select_data()

    def retranslateUi(self, AddDependent):
        _translate = QtCore.QCoreApplication.translate
        AddDependent.setWindowTitle(_translate("AddDependent", "AddDependent"))
        self.tabdependents.setSortingEnabled(True)
        item = self.tabdependents.horizontalHeaderItem(0)
        item.setText(_translate("AddDependent", "Name"))
        item = self.tabdependents.horizontalHeaderItem(1)
        item.setText(_translate("AddDependent", "Sex"))
        item = self.tabdependents.horizontalHeaderItem(2)
        item.setText(_translate("AddDependent", "Date of Birth"))
        item = self.tabdependents.horizontalHeaderItem(3)
        item.setText(_translate("AddDependent", "Relationship"))
        self.label_2.setText(_translate("AddDependent", "Name"))
        self.gobutton.setText(_translate("AddDependent", "Go"))
        self.label_5.setText(_translate("AddDependent", "Relationship"))
        self.label_4.setText(_translate("AddDependent", "Date of Birth"))
        self.label_3.setText(_translate("AddDependent", "Sex"))
        self.label.setText(_translate("AddDependent", "Emp SSN"))
        self.empname.setText(_translate("AddDependent", "Emp Name"))
        self.label_6.setText(_translate("AddDependent", "Dependent Count"))

    def select_data(self):
        try:
            print("select dependents")
            db = mysql.connector.connect(option_files='mydb.conf')
            cursor = db.cursor()
            cursor.execute("select concat(fname, ' ', minit,' ', lname) empname from employee where ssn =" + str(self.passedssn))
            for row in cursor:
                print(row)
                self.empname_2.setText(row[0])
            self.empname_2.setDisabled(True)
            nrows = cursor.rowcount
            print('nrows', nrows)
            if nrows <= 0 :
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("No employee with ssn "+ str(self.passedssn))
                msg.setWindowTitle("Add Dependent")
                msg.exec()
                return

            cursor.execute("select dependent_name, sex, bdate, relationship from dependent where essn =" + str(self.passedssn))
            result = cursor.fetchall()
            nrows = cursor.rowcount
            self.depcount.setText(str(nrows))
            self.depcount.setDisabled(True)
            self.tabdependents.setRowCount(0)
            for rnum, rdata in enumerate(result):
                self.tabdependents.insertRow(rnum)
                for colnum, cdata in enumerate(rdata):
                    self.tabdependents.setItem(rnum, colnum,QTableWidgetItem(str(cdata)))
            self.tabdependents.setDisabled(True)
        except mysql.connector.Error as e:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("SQL Error "+ str(e.msg))
            msg.setWindowTitle("Add Dependent")
            msg.exec()

    def processinsert(self):
        print("insert dep")
        try:
            db = mysql.connector.connect(option_files='mydb.conf')
            cursor = db.cursor()

            cursor.execute("select b.* from dependent b where b.dependent_name = '"+str(self.dname.toPlainText()) +"' and b.essn = " + \
                self.empssn.text() )
            cursor.fetchall()
            print(cursor.rowcount)

            if cursor.rowcount > 0:
                # Case for duplicate dep
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Dependent " + str(self.dname) + " already in DB for Emp " + str(self.empssn.text()))
                msg.setWindowTitle("Add Dependent")
                msg.exec()
                cursor.close()
                #msg.setDetailedText("The details are as follows:")
            else:
                # iterate over result
            
                depname = self.dname.toPlainText()
                essn = self.empssn.text()
                dob = self.dateofbirth.date()
                print(dob.getDate())
                sx = self.sex.currentText()
                rel = self.relationship.toPlainText()

                sql = "insert into dependent (essn, dependent_name, bdate, sex, relationship)" \
                    " VALUES (%s, %s, %s, %s, %s)"
                val = (essn,depname,dob.toString("yyyy/MM/dd"),sx,rel)
                cursor.close()
                if depname is None:
                    msg = QtWidgets.QMessageBox()
                    msg.setIcon(QMessageBox.Information)
                    msg.setText("Dependent Name is mandatory")
                    msg.setWindowTitle("Add Dependent")
                    msg.exec()
                    cursor.close()
                else:
                    cursor = db.cursor()
                    cursor.execute(sql, val)
                    db.commit()
                    db.close()
                    msg = QtWidgets.QMessageBox()
                    msg.setIcon(QMessageBox.Information)
                    msg.setText("Dependent "+ str(depname) + " added")
                    msg.setWindowTitle("Add Dependent")
                    msg.exec()
                    #self.tabdependents.insertRow()
        
            db.close()
            self.select_data()
        
        except mysql.connector.Error as e:
            db.close()
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("SQL Error "+ str(e.msg))
            msg.setWindowTitle("Add Dependent")
            msg.exec() 
