# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'empdetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# This code handles the menu item Add New Employee 

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql.connector
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

class Ui_AddEmployee():
    passedssn = 123456789  # fix later
    def __init__(self):
        self.passedssn = 123456789  # fix later

    def setupUi(self, AddEmployee):
        AddEmployee.setObjectName("AddEmployee")
        AddEmployee.resize(719, 537)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddEmployee)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)

        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.firstname = QtWidgets.QTextEdit(AddEmployee)
        self.firstname.setGeometry(QtCore.QRect(70, 60, 211, 31))
        self.firstname.setObjectName("firstname")
        self.label = QtWidgets.QLabel(AddEmployee)
        self.label.setGeometry(QtCore.QRect(70, 40, 81, 16))
        self.label.setObjectName("label")
        self.lastname = QtWidgets.QTextEdit(AddEmployee)
        self.lastname.setGeometry(QtCore.QRect(420, 60, 211, 31))
        self.lastname.setObjectName("lastname")
        self.label_2 = QtWidgets.QLabel(AddEmployee)
        self.label_2.setGeometry(QtCore.QRect(420, 40, 81, 16))
        self.label_2.setObjectName("label_2")
        self.middleinitial = QtWidgets.QTextEdit(AddEmployee)
        self.middleinitial.setGeometry(QtCore.QRect(310, 60, 71, 31))
        self.middleinitial.setObjectName("middleinitial")
        self.label_3 = QtWidgets.QLabel(AddEmployee)
        self.label_3.setGeometry(QtCore.QRect(310, 40, 81, 16))
        self.label_3.setObjectName("label_3")
        self.empssn = QtWidgets.QLineEdit(AddEmployee)
        self.empssn.setGeometry(QtCore.QRect(70, 140, 131, 31))
        self.empssn.setObjectName("empssn")
        self.label_4 = QtWidgets.QLabel(AddEmployee)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 55, 16))
        self.label_4.setObjectName("label_4")
        self.dateofbirth = QtWidgets.QDateEdit(AddEmployee)
        self.dateofbirth.setGeometry(QtCore.QRect(240, 140, 111, 31))
        self.dateofbirth.setObjectName("dateofbirth")
        self.label_5 = QtWidgets.QLabel(AddEmployee)
        self.label_5.setGeometry(QtCore.QRect(240, 120, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AddEmployee)
        self.label_6.setGeometry(QtCore.QRect(70, 200, 55, 16))
        self.label_6.setObjectName("label_6")
        self.address = QtWidgets.QTextEdit(AddEmployee)
        self.address.setGeometry(QtCore.QRect(70, 220, 561, 31))
        self.address.setObjectName("address")
        self.sex = QtWidgets.QComboBox(AddEmployee)
        self.sex.setGeometry(QtCore.QRect(70, 300, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.sex.setSizePolicy(sizePolicy)
        #self.sex.setEditable(False)
        self.sex.setCurrentText("")
        self.sex.addItem("M")
        self.sex.addItem("F")
        self.sex.setMaxCount(2)
        self.sex.setObjectName("sex")
        self.label_7 = QtWidgets.QLabel(AddEmployee)
        self.label_7.setGeometry(QtCore.QRect(70, 280, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(AddEmployee)
        self.label_8.setGeometry(QtCore.QRect(220, 280, 55, 16))
        self.label_8.setObjectName("label_8")
        self.salary = QtWidgets.QTextEdit(AddEmployee)
        self.salary.setGeometry(QtCore.QRect(220, 300, 131, 31))
        self.salary.setObjectName("salary")
        self.label_9 = QtWidgets.QLabel(AddEmployee)
        self.label_9.setGeometry(QtCore.QRect(430, 280, 111, 16))
        self.label_9.setObjectName("label_9")
        self.label_9.setVisible(False)   # ??
        self.supssn = QtWidgets.QTextEdit(AddEmployee)
        self.supssn.setGeometry(QtCore.QRect(430, 300, 131, 31))
        self.supssn.setObjectName("supssn")
        self.supssn.setVisible(False)
        
        #self.deptname = QtWidgets.QTextEdit(AddEmployee)
        #self.deptname.setGeometry(QtCore.QRect(220, 380, 171, 31))
        #self.deptname.setObjectName("deptname")
        
        self.deptname = QtWidgets.QComboBox(AddEmployee)
        self.deptname.setGeometry(QtCore.QRect(220, 380, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.deptname.setSizePolicy(sizePolicy)
        #self.deptname.setEditable(False)
        self.deptname.setCurrentText("")
        self.deptname.setObjectName("deptname")
        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()
        # This code is the code that finds the information for department name
        cursor.execute("select concat(s.dnumber, ':', s.dname) dName  from department s order by dname")
        for row in cursor:
            self.deptname.addItem(row[0])

        
        self.label_10 = QtWidgets.QLabel(AddEmployee)
        self.label_10.setGeometry(QtCore.QRect(70, 360, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_10.setVisible(False)   #
        self.label_11 = QtWidgets.QLabel(AddEmployee)
        self.label_11.setGeometry(QtCore.QRect(220, 360, 131, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(AddEmployee)
        self.label_12.setGeometry(QtCore.QRect(430, 360, 131, 16))
        self.label_12.setObjectName("label_12")
        self.deptno = QtWidgets.QTextEdit(AddEmployee)
        self.deptno.setGeometry(QtCore.QRect(70, 380, 81, 31))
        self.deptno.setObjectName("deptno")
        self.deptno.setVisible(False)

        #self.supervisorname = QtWidgets.QTextEdit(AddEmployee)
        #self.supervisorname.setGeometry(QtCore.QRect(430, 380, 171, 31))
        self.supervisorname = QtWidgets.QComboBox(AddEmployee)
        self.supervisorname.setGeometry(QtCore.QRect(430, 380, 180, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.supervisorname.setSizePolicy(sizePolicy)
        #self.supervisorname.setEditable(False)
        self.supervisorname.setCurrentText("")
        self.supervisorname.setObjectName("supervisorname")
        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()
        
        cursor.execute("select concat(s.ssn, ':', s.fname, ' ', s.minit, ' ', s.lname) ssnName  from employee s order by lname")
        for row in cursor:
            self.supervisorname.addItem(row[0])

        self.gobutton = QtWidgets.QPushButton(AddEmployee)
        self.gobutton.setGeometry(QtCore.QRect(70, 440, 93, 28))
        self.gobutton.setObjectName("gobutton")

        self.retranslateUi(AddEmployee)
        self.buttonBox.rejected.connect(AddEmployee.reject)
        self.gobutton.clicked.connect(self.processinsert)
        QtCore.QMetaObject.connectSlotsByName(AddEmployee)

        reg_ex = QRegExp("[0-9]{9}")
        input_validator = QRegExpValidator(reg_ex, self.empssn)
        self.empssn.setValidator(input_validator)    
        
    def retranslateUi(self, AddEmployee):
        _translate = QtCore.QCoreApplication.translate
        AddEmployee.setWindowTitle(_translate("AddEmployee", "Employee Details"))
        self.label.setText(_translate("AddEmployee", "First Name"))
        self.label_2.setText(_translate("AddEmployee", "Last Name"))
        self.label_3.setText(_translate("AddEmployee", "M.I."))
        self.label_4.setText(_translate("AddEmployee", "SSN"))
        self.label_5.setText(_translate("AddEmployee", "Date of Birth"))
        self.label_6.setText(_translate("AddEmployee", "Address"))
        self.label_7.setText(_translate("AddEmployee", "Sex"))
        self.label_8.setText(_translate("AddEmployee", "Salary"))
        self.label_9.setText(_translate("AddEmployee", "Supervisor SSN"))
        self.label_10.setText(_translate("AddEmployee", "Dept No"))
        self.label_11.setText(_translate("AddEmployee", "Department Name"))
        self.label_12.setText(_translate("AddEmployee", "Supervisor Name"))
        self.gobutton.setText(_translate("MainWindow", "Go"))
# This is the function which actually constructs the sql query for adding the employee to the table
    def processinsert(self):
        print("insert proc")
# Create db connection using information for the database in mydb.conf 
        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()

        cursor.execute("select a.*, b.dname, concat(s.fname, ' ', s.minit, ' ', s.lname) sname " + " from employee a, department b, employee s where a.ssn = "+
           str(self.empssn.text()) + " and a.dno = b.dnumber and a.super_ssn = s.ssn")
        cursor.fetchall()
        print(cursor.rowcount)

        if cursor.rowcount > 0:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("SSN already in DB")
            msg.setWindowTitle("Add Employee")
            msg.exec()
            cursor.close()
            #msg.setDetailedText("The details are as follows:")
        else:
            # iterate over result
            # Create variables for all of the attribute values of the new employee by taking
            # the entered values and turning them into text
            fname = self.firstname.toPlainText()
            minit = self.middleinitial.toPlainText()+''
            lname = self.lastname.toPlainText()
            essn = self.empssn.text()
            dob = self.dateofbirth.date()
            print(dob.getDate())
            addr = self.address.toPlainText()
            sx = self.sex.currentText()
            sal=self.salary.toPlainText()
            dname = self.deptname.currentText()
            dno = dname[0:dname.index(':')]
            dname = dname[dname.index(':')+1:]
            print(dno, dname)
            supname = self.supervisorname.currentText()
            spssn = supname[0:supname.index(':')]
            supname = supname[supname.index(':')+1:]
            print(dno, dname)
# This statement creates the INSERT sql query that places the new employee tuple in the db
            sql = "insert into employee (fname, minit, lname, ssn, bdate, address, sex, salary, super_ssn, dno)" \
                  " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
            val = (fname, minit, lname, essn, dob.toString("yyyy/MM/dd"),addr,sx,sal,spssn,dno)
            cursor.close()
            # SSN is primary key so a value must be given
            if essn is None:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("SSN mandatory")
                msg.setWindowTitle("Add Employee")
                msg.exec()
                cursor.close()
            else:
                cursor = db.cursor()
                cursor.execute(sql, val)
                db.commit()
                db.close()
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("Employee "+ str(lname) + " added")
                msg.setWindowTitle("Add Employee")
                msg.exec()
      
        db.close()
 
if __name__ == "__main__":
    import sys
    print("in dbproject main")
    app = QtWidgets.QApplication(sys.argv)
    AddEmployee = QtWidgets.QDialog()
    ui = Ui_AddEmployee()
    ui.setupUi(AddEmployee)
    AddEmployee.show()
    sys.exit(app.exec_())

