# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dbproject2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from empdetails import Ui_EmployeeDetails
from addemployee import Ui_AddEmployee
from modempdetails import Ui_ModifyEmployee
from adddependent import Ui_AddDependent
from viewdependents import Ui_ViewDependents
from DelEmployee import Ui_DelEmployee
from removedependent import Ui_RemoveDependent
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtCore import QRegExp
import mysql.connector
from PyQt5.QtWidgets import QMessageBox, QDialog



class Ui_MainWindow(object):
    def __init(self):
        reqtype = 2

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        ####
        #MainWindow.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
        #                                         QtWidgets.QSizePolicy.MinimumExpanding))
        MainWindow.setMinimumSize(QtCore.QSize(1055, 680))
        MainWindow.setMaximumSize(QtCore.QSize(1055, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 80, 691, 541))
        self.groupBox.setObjectName("groupBox")
        self.gobutton = QtWidgets.QPushButton(self.groupBox)
        self.gobutton.setGeometry(QtCore.QRect(100, 450, 93, 28))
        self.gobutton.setObjectName("gobutton")
        self.exitbutton = QtWidgets.QPushButton(self.groupBox)
        self.exitbutton.setGeometry(QtCore.QRect(540, 450, 93, 28))
        self.exitbutton.setObjectName("exitbutton")
        self.textEdit = QtWidgets.QLineEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(370, 140, 231, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(370, 120, 340, 16))    ####
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(100, 60, 360, 351))   ####
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addnewemployee = QtWidgets.QRadioButton(self.widget)
        self.addnewemployee.setObjectName("addnewemployee")
        self.verticalLayout.addWidget(self.addnewemployee)
        self.empdetails = QtWidgets.QRadioButton(self.widget)
        self.empdetails.setObjectName("empdetails")
        self.verticalLayout.addWidget(self.empdetails)
        self.adddependent = QtWidgets.QRadioButton(self.widget)
        self.adddependent.setObjectName("adddependent")
        self.verticalLayout.addWidget(self.adddependent)
        self.viewdependent = QtWidgets.QRadioButton(self.widget)
        self.viewdependent.setObjectName("viewdependent")
        self.verticalLayout.addWidget(self.viewdependent)
        self.modifyemployee = QtWidgets.QRadioButton(self.widget)
        self.modifyemployee.setObjectName("modifyemployee")
        self.verticalLayout.addWidget(self.modifyemployee)
        self.removedependent = QtWidgets.QRadioButton(self.widget)
        self.removedependent.setObjectName("removedependent")
        self.verticalLayout.addWidget(self.removedependent)
        self.removeemployee = QtWidgets.QRadioButton(self.widget)
        self.removeemployee.setObjectName("removeemployee")
        self.verticalLayout.addWidget(self.removeemployee)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # add dialogs here
        self.EmployeeDetails = QtWidgets.QDialog()
        self.AddEmployee = QtWidgets.QDialog()
        self.ModifyEmployee = QtWidgets.QDialog()
        self.AddDependent = QtWidgets.QDialog()
        self.ViewDependents = QtWidgets.QDialog()
        self.RemoveDependent = QtWidgets.QDialog()
        self.DelEmployee = QtWidgets.QDialog()
        
        reg_ex = QRegExp("[0-9]{9}")
        input_validator = QRegExpValidator(reg_ex, self.textEdit)
        self.textEdit.setValidator(input_validator)    
        
        self.exitbutton.clicked.connect(self.exitpgm)
        self.gobutton.clicked.connect(self.processrequest)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Database project 2"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.gobutton.setText(_translate("MainWindow", "Go"))
        self.exitbutton.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "SSN needed except for Add Employee"))
        self.addnewemployee.setText(_translate("MainWindow", "Add New Employee"))
        self.empdetails.setText(_translate("MainWindow", "View Employee Details"))
        self.empdetails.toggle()
        self.adddependent.setText(_translate("MainWindow", "Add Dependent"))
        self.viewdependent.setText(_translate("MainWindow", "View Dependents"))
        self.modifyemployee.setText(_translate("MainWindow", "Modify Employee"))
        self.removedependent.setText(_translate("MainWindow", "Remove Dependent"))
        self.removeemployee.setText(_translate("MainWindow", "Remove Employee"))
    
    def exitpgm(self):
        sys.exit()

    def processrequest(self):
        if not self.addnewemployee.isChecked():
            db = mysql.connector.connect(option_files="mydb.conf")
            cursor = db.cursor()
            nrows = 0
            if str(self.textEdit.text()) != "":
                cursor.execute("select concat(fname, ' ', minit,' ', lname) empname from employee where ssn =" + str(self.textEdit.text()))
                for row in cursor:
                    print(row)
                nrows = cursor.rowcount
            print('nrows', nrows)
            if nrows <= 0 :
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("No employee with ssn '"+ str(self.textEdit.text())+"'")
                msg.setWindowTitle("Employee not found")
                msg.exec()
                return

        if self.addnewemployee.isChecked():
            reqtype = 1
            ui = Ui_AddEmployee()
            ui.setupUi(self.AddEmployee)
            self.AddEmployee.exec()
        elif self.empdetails.isChecked():
            reqtype = 2
            ui = Ui_EmployeeDetails(self)
            ui.setupUi(self.EmployeeDetails)
            self.EmployeeDetails.show()
        elif self.adddependent.isChecked():
            reqtype = 3
            ui = Ui_AddDependent(self)
            ui.setupUi(self.AddDependent)
            self.AddDependent.exec()
        elif self.viewdependent.isChecked():
            reqtype = 4
            ui = Ui_ViewDependents(self)
            ui.setupUi(self.ViewDependents)
            self.ViewDependents.exec()
        elif self.modifyemployee.isChecked():
            reqtype = 5
            ui = Ui_ModifyEmployee(self)
            ui.setupUi(self.ModifyEmployee)
            self.ModifyEmployee.exec()
        elif self.removedependent.isChecked():
            reqtype = 6
            ui = Ui_RemoveDependent(self)
            ui.setupUi(self.RemoveDependent)
            self.RemoveDependent.exec()
        elif self.removeemployee.isChecked():
            reqtype = 7
            ui = Ui_DelEmployee(self)
            ui.setupUi(self.DelEmployee)
            self.DelEmployee.exec()
        
if __name__ == "__main__":
    import sys
    import PyQt5
    if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
        PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
        PyQt5.QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
