# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DelEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QDialog
from PyQt5.QtWidgets import QTableWidgetItem, QApplication
import mysql.connector
from PyQt5.QtCore import QRegExp, Qt
from PyQt5.QtGui import QRegExpValidator


class Ui_DelEmployee(QDialog):
    passedssn = -1
    nrows = -1
    def __init__(self, obj):
        super(Ui_DelEmployee, self).__init__()
        self.passedssn = obj.textEdit.text()
    
    def setupUi(self, DelEmployee):
        DelEmployee.setObjectName("DelEmployee")
        DelEmployee.resize(699, 433)
        self.buttonBox = QtWidgets.QDialogButtonBox(DelEmployee)
        self.buttonBox.setGeometry(QtCore.QRect(300, 360, 321, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(DelEmployee)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 80, 641, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabdependents = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tabdependents.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabdependents.sizePolicy().hasHeightForWidth())
        self.tabdependents.setSizePolicy(sizePolicy)
        self.tabdependents.setMinimumSize(QtCore.QSize(639, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabdependents.setFont(font)
        self.tabdependents.setAutoFillBackground(True)
        self.tabdependents.setGridStyle(QtCore.Qt.SolidLine)
        self.tabdependents.setRowCount(10)
        self.tabdependents.setColumnCount(4)
        self.tabdependents.setObjectName("tabdependents")
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(3, item)
        self.tabdependents.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tabdependents)
        self.empssn = QtWidgets.QLineEdit(DelEmployee)
        self.empssn.setGeometry(QtCore.QRect(90, 20, 101, 31))
        self.empssn.setObjectName("empssn")
        self.gobutton = QtWidgets.QPushButton(DelEmployee)
        self.gobutton.setGeometry(QtCore.QRect(30, 360, 93, 28))
        self.gobutton.setObjectName("gobutton")
        self.label = QtWidgets.QLabel(DelEmployee)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.label.setObjectName("label")
        self.empname = QtWidgets.QLabel(DelEmployee)
        self.empname.setGeometry(QtCore.QRect(240, 20, 71, 21))
        self.empname.setObjectName("empname")
        self.empname_2 = QtWidgets.QTextEdit(DelEmployee)
        self.empname_2.setGeometry(QtCore.QRect(310, 20, 261, 31))
        self.empname_2.setObjectName("empname_2")
        self.label_6 = QtWidgets.QLabel(DelEmployee)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 121, 16))
        self.label_6.setObjectName("label_6")
        self.depcount = QtWidgets.QTextEdit(DelEmployee)
        self.depcount.setGeometry(QtCore.QRect(210, 300, 31, 31))
        self.depcount.setObjectName("depcount")

        self.empssn.setText(self.passedssn)
        self.empssn.setDisabled(True)
        
        self.retranslateUi(DelEmployee)
        self.buttonBox.rejected.connect(DelEmployee.reject)
        self.gobutton.clicked.connect(self.processdelete)
        QtCore.QMetaObject.connectSlotsByName(DelEmployee)
       
        self.select_data()

    def retranslateUi(self, DelEmployee):
        _translate = QtCore.QCoreApplication.translate
        DelEmployee.setWindowTitle(_translate("DelEmployee", "Dialog"))
        self.tabdependents.setSortingEnabled(True)
        item = self.tabdependents.horizontalHeaderItem(0)
        item.setText(_translate("DelEmployee", "Name"))
        item = self.tabdependents.horizontalHeaderItem(1)
        item.setText(_translate("DelEmployee", "Sex"))
        item = self.tabdependents.horizontalHeaderItem(2)
        item.setText(_translate("DelEmployee", "Date of Birth"))
        item = self.tabdependents.horizontalHeaderItem(3)
        item.setText(_translate("DelEmployee", "Relationship"))
        self.gobutton.setText(_translate("DelEmployee", "Delete"))
        self.label.setText(_translate("DelEmployee", "Emp SSN"))
        self.empname.setText(_translate("DelEmployee", "Emp Name"))
        self.label_6.setText(_translate("DelEmployee", "Dependent Count"))

    def select_data(self):
        try:
            #print("select dependents")
            db = mysql.connector.connect(option_files='mydb.conf')
            cursor = db.cursor()
            cursor.execute("select concat(fname, ' ', minit,' ', lname) empname from employee where ssn =" + str(self.passedssn))
            for row in cursor:
                #print(row)
                self.empname_2.setText(row[0])
            self.empname_2.setDisabled(True)
            nrows = cursor.rowcount
            #print('nrows', nrows)
            if nrows <= 0 :
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("No employee with ssn "+ str(self.passedssn))
                msg.setWindowTitle("Add Dependent")
                msg.exec()
                self.reject()

            cursor.execute("select dependent_name, sex, bdate, relationship from dependent where essn =" + str(self.passedssn))
            result = cursor.fetchall()
            self.nrows = cursor.rowcount
            self.depcount.setText(str(nrows))
            self.depcount.setDisabled(True)
            self.tabdependents.setRowCount(0)
            for rnum, rdata in enumerate(result):
                self.tabdependents.insertRow(rnum)
                for colnum, cdata in enumerate(rdata):
                    self.tabdependents.setItem(rnum, colnum,QTableWidgetItem(str(cdata)))
            self.tabdependents.setDisabled(True)
        except mysql.connector.Error as e:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("SQL Error "+ str(e.msg))
            msg.setWindowTitle("Add Dependent")
            msg.exec()

    def processdelete(self):
        #print("delete emp")
        try:
            print('delrows', self.nrows)
            if self.nrows > 0 :
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("delete employee dependents first for ssn "+ str(self.passedssn))
                msg.setWindowTitle("Delete Employee")
                msg.exec()

            else:
                db = mysql.connector.connect(option_files='mydb.conf')
                cursor = db.cursor()
                QApplication.setOverrideCursor(Qt.WaitCursor)
                cursor.execute("SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; START TRANSACTION;", multi=True)
                #print("start tran")
                cursor.execute("delete from employee where ssn =" + str(self.passedssn))
                #print("deleted emp")
                nrows = cursor.rowcount
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                if nrows > 0:
                    msg.setText("Deleted employee with ssn "+ str(self.passedssn))
                else:
                    msg.setText("Employee not found "+ str(self.passedssn) + " deleted by another session?")
                msg.setWindowTitle("Delete Employee")
                msg.exec()
                db.commit()
                QApplication.restoreOverrideCursor()

        except mysql.connector.Error as e:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("SQL Error "+ str(e.msg))
            msg.setWindowTitle("Delete Employee")
            msg.exec()
            QApplication.restoreOverrideCursor()
     
    def reject(self):
        print("reject")  # test
        self.VDep.close()
 
