# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'empdetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_EmployeeDetails(object):
    passedssn = -1
    def __init__(self, obj):
        self.passedssn = obj.textEdit.text() # Main window is passed directly as ssn variable

    def setupUi(self, EmployeeDetails):
        EmployeeDetails.setObjectName("EmployeeDetails")
        EmployeeDetails.resize(719, 537)
        self.buttonBox = QtWidgets.QDialogButtonBox(EmployeeDetails)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.firstname = QtWidgets.QTextEdit(EmployeeDetails)
        self.firstname.setGeometry(QtCore.QRect(70, 60, 211, 31))
        self.firstname.setObjectName("firstname")        
        self.firstname.setDisabled(True)
        self.label = QtWidgets.QLabel(EmployeeDetails)
        self.label.setGeometry(QtCore.QRect(70, 40, 81, 16))
        self.label.setObjectName("label")
        self.lastname = QtWidgets.QTextEdit(EmployeeDetails)
        self.lastname.setGeometry(QtCore.QRect(420, 60, 211, 31))
        self.lastname.setObjectName("lastname")
        self.lastname.setDisabled(True)
        self.label_2 = QtWidgets.QLabel(EmployeeDetails)
        self.label_2.setGeometry(QtCore.QRect(420, 40, 81, 16))
        self.label_2.setObjectName("label_2")
        self.middleinitial = QtWidgets.QTextEdit(EmployeeDetails)
        self.middleinitial.setGeometry(QtCore.QRect(310, 60, 71, 31))
        self.middleinitial.setObjectName("middleinitial")
        self.middleinitial.setDisabled(True)
        self.label_3 = QtWidgets.QLabel(EmployeeDetails)
        self.label_3.setGeometry(QtCore.QRect(310, 40, 81, 16))
        self.label_3.setObjectName("label_3")
        self.empssn = QtWidgets.QTextEdit(EmployeeDetails)
        self.empssn.setGeometry(QtCore.QRect(70, 140, 131, 31))
        self.empssn.setObjectName("empssn")
        self.empssn.setDisabled(True)
        self.label_4 = QtWidgets.QLabel(EmployeeDetails)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 55, 16))
        self.label_4.setObjectName("label_4")
        self.dateofbirth = QtWidgets.QDateEdit(EmployeeDetails)
        self.dateofbirth.setGeometry(QtCore.QRect(240, 140, 111, 31))
        self.dateofbirth.setObjectName("dateofbirth")
        self.dateofbirth.setDisabled(True)
        self.label_5 = QtWidgets.QLabel(EmployeeDetails)
        self.label_5.setGeometry(QtCore.QRect(240, 120, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(EmployeeDetails)
        self.label_6.setGeometry(QtCore.QRect(70, 200, 55, 16))
        self.label_6.setObjectName("label_6")
        self.address = QtWidgets.QTextEdit(EmployeeDetails)
        self.address.setGeometry(QtCore.QRect(70, 220, 561, 31))
        self.address.setObjectName("address")
        self.address.setDisabled(True)
        self.sex = QtWidgets.QComboBox(EmployeeDetails)
        self.sex.setGeometry(QtCore.QRect(70, 300, 71, 31))
        self.sex.setDisabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.sex.setSizePolicy(sizePolicy)
        #self.sex.setEditable(False)
        self.sex.setCurrentText("")
        self.sex.addItem("M")
        self.sex.addItem("F")
        self.sex.setMaxCount(2)
        self.sex.setObjectName("sex")
        self.label_7 = QtWidgets.QLabel(EmployeeDetails)
        self.label_7.setGeometry(QtCore.QRect(70, 280, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(EmployeeDetails)
        self.label_8.setGeometry(QtCore.QRect(220, 280, 55, 16))
        self.label_8.setObjectName("label_8")
        self.salary = QtWidgets.QTextEdit(EmployeeDetails)
        self.salary.setGeometry(QtCore.QRect(220, 300, 131, 31))
        self.salary.setObjectName("salary")
        self.salary.setDisabled(True)
        self.label_9 = QtWidgets.QLabel(EmployeeDetails)
        self.label_9.setGeometry(QtCore.QRect(430, 280, 111, 16))
        self.label_9.setObjectName("label_9")
        self.supssn = QtWidgets.QTextEdit(EmployeeDetails)
        self.supssn.setGeometry(QtCore.QRect(430, 300, 131, 31))
        self.supssn.setObjectName("supssn")
        self.supssn.setDisabled(True)
        self.deptname = QtWidgets.QTextEdit(EmployeeDetails)
        self.deptname.setGeometry(QtCore.QRect(220, 380, 171, 31))
        self.deptname.setObjectName("deptname")
        self.deptname.setDisabled(True)
        self.label_10 = QtWidgets.QLabel(EmployeeDetails)
        self.label_10.setGeometry(QtCore.QRect(70, 360, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(EmployeeDetails)
        self.label_11.setGeometry(QtCore.QRect(220, 360, 131, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(EmployeeDetails)
        self.label_12.setGeometry(QtCore.QRect(430, 360, 131, 16))
        self.label_12.setObjectName("label_12")
        self.deptno = QtWidgets.QTextEdit(EmployeeDetails)
        self.deptno.setGeometry(QtCore.QRect(70, 380, 81, 31))
        self.deptno.setObjectName("deptno")
        self.deptno.setDisabled(True)
        self.supervisorname = QtWidgets.QTextEdit(EmployeeDetails)
        self.supervisorname.setGeometry(QtCore.QRect(430, 380, 171, 31))
        self.supervisorname.setObjectName("supervisorname")
        self.supervisorname.setDisabled(True)

        self.retranslateUi(EmployeeDetails)
        self.buttonBox.accepted.connect(EmployeeDetails.accept)
        self.buttonBox.rejected.connect(EmployeeDetails.reject)
        QtCore.QMetaObject.connectSlotsByName(EmployeeDetails)

        #db = mysql.connector.connect(host="localhost", user="root",
        #        passwd="USmysql123!", database="companydb")
        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()
        #This query just uses SELECT to retrieve details about an employee based off details provided
        # by the menu
        cursor.execute("select a.*, b.dname, concat(s.fname, ' ', s.minit, ' ', s.lname) sname " + " from employee a, department b, employee s where a.ssn = "+
           self.passedssn + " and a.dno = b.dnumber and a.super_ssn = s.ssn")

        # iterate over result
        for row in cursor:
            print(row)
            self.firstname.setText(row[0])
            self.middleinitial.setText(row[1])
            self.lastname.setText(row[2])
            self.empssn.setText(row[3])
            self.dateofbirth.setDate(row[4])
            self.address.setText(row[5])
            index = self.sex.findText(row[6], QtCore.Qt.MatchFixedString)
            if index >= 0:
                self.sex.setCurrentIndex(index)
            self.salary.setText(str(row[7]))
            self.supssn.setText(str(row[8]))
            self.deptno.setText(str(row[9]))
            self.deptname.setText(row[10])
            self.supervisorname.setText(row[11])

        #cursor.execute("select * from department where dnumber = "+self.deptno.toPlainText())
        ##for row in cursor:
        #    print(row)
        #    self.deptname.setText(row[0])

        cursor.close()
        db.close()

    def retranslateUi(self, EmployeeDetails):
        _translate = QtCore.QCoreApplication.translate
        EmployeeDetails.setWindowTitle(_translate("EmployeeDetails", "Employee Details"))
        self.label.setText(_translate("EmployeeDetails", "First Name"))
        self.label_2.setText(_translate("EmployeeDetails", "Last Name"))
        self.label_3.setText(_translate("EmployeeDetails", "M.I."))
        self.label_4.setText(_translate("EmployeeDetails", "SSN"))
        self.label_5.setText(_translate("EmployeeDetails", "Date of Birth"))
        self.label_6.setText(_translate("EmployeeDetails", "Address"))
        self.label_7.setText(_translate("EmployeeDetails", "Sex"))
        self.label_8.setText(_translate("EmployeeDetails", "Salary"))
        self.label_9.setText(_translate("EmployeeDetails", "Supervisor SSN"))
        self.label_10.setText(_translate("EmployeeDetails", "Dept No"))
        self.label_11.setText(_translate("EmployeeDetails", "Department Name"))
        self.label_12.setText(_translate("EmployeeDetails", "Supervisor Name"))


if __name__ == "__main__":
    import sys
    print("in dbproject main")
    app = QtWidgets.QApplication(sys.argv)
    EmployeeDetails = QtWidgets.QDialog()
    ui = Ui_EmployeeDetails()
    ui.setupUi(EmployeeDetails)
    EmployeeDetails.show()
    #sys.exit(app.exec_())
