# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'empdetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QApplication
from PyQt5.QtCore import QRegExp, Qt
import mysql.connector

class Ui_ModifyEmployee():
    passedssn = 123456789  # 
    ModDep = None
    def __init__(self, obj):
        self.passedssn = obj.textEdit.text()

    def setupUi(self, ModifyEmployee):
        self.ModDep = ModifyEmployee
        ModifyEmployee.setObjectName("ModifyEmployee")
        ModifyEmployee.resize(719, 537)
        self.buttonBox = QtWidgets.QDialogButtonBox(ModifyEmployee)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)

        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.firstname = QtWidgets.QTextEdit(ModifyEmployee)
        self.firstname.setGeometry(QtCore.QRect(70, 60, 211, 31))
        self.firstname.setObjectName("firstname")
        self.firstname.setDisabled(True)
        self.label = QtWidgets.QLabel(ModifyEmployee)
        self.label.setGeometry(QtCore.QRect(70, 40, 81, 16))
        self.label.setObjectName("label")
        self.lastname = QtWidgets.QTextEdit(ModifyEmployee)
        self.lastname.setGeometry(QtCore.QRect(420, 60, 211, 31))
        self.lastname.setObjectName("lastname")
        self.lastname.setDisabled(True)
        self.label_2 = QtWidgets.QLabel(ModifyEmployee)
        self.label_2.setGeometry(QtCore.QRect(420, 40, 81, 16))
        self.label_2.setObjectName("label_2")
        self.middleinitial = QtWidgets.QTextEdit(ModifyEmployee)
        self.middleinitial.setGeometry(QtCore.QRect(310, 60, 71, 31))
        self.middleinitial.setObjectName("middleinitial")
        self.middleinitial.setDisabled(True)
        self.label_3 = QtWidgets.QLabel(ModifyEmployee)
        self.label_3.setGeometry(QtCore.QRect(310, 40, 81, 16))
        self.label_3.setObjectName("label_3")
        self.empssn = QtWidgets.QTextEdit(ModifyEmployee)
        self.empssn.setGeometry(QtCore.QRect(70, 140, 131, 31))
        self.empssn.setObjectName("empssn")
        self.empssn.setDisabled(True)
        self.label_4 = QtWidgets.QLabel(ModifyEmployee)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 55, 16))
        self.label_4.setObjectName("label_4")
        self.dateofbirth = QtWidgets.QDateEdit(ModifyEmployee)
        self.dateofbirth.setGeometry(QtCore.QRect(240, 140, 111, 31))
        self.dateofbirth.setObjectName("dateofbirth")
        self.dateofbirth.setDisabled(True)
        self.label_5 = QtWidgets.QLabel(ModifyEmployee)
        self.label_5.setGeometry(QtCore.QRect(240, 120, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ModifyEmployee)
        self.label_6.setGeometry(QtCore.QRect(70, 200, 55, 16))
        self.label_6.setObjectName("label_6")
        self.address = QtWidgets.QTextEdit(ModifyEmployee)
        self.address.setGeometry(QtCore.QRect(70, 220, 561, 31))
        self.address.setObjectName("address")
        self.sex = QtWidgets.QComboBox(ModifyEmployee)
        self.sex.setGeometry(QtCore.QRect(70, 300, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.sex.setSizePolicy(sizePolicy)
        #self.sex.setEditable(False)
        self.sex.setCurrentText("")
        self.sex.addItem("M")
        self.sex.addItem("F")
        self.sex.setMaxCount(2)
        self.sex.setObjectName("sex")
        self.label_7 = QtWidgets.QLabel(ModifyEmployee)
        self.label_7.setGeometry(QtCore.QRect(70, 280, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ModifyEmployee)
        self.label_8.setGeometry(QtCore.QRect(220, 280, 55, 16))
        self.label_8.setObjectName("label_8")
        self.salary = QtWidgets.QTextEdit(ModifyEmployee)
        self.salary.setGeometry(QtCore.QRect(220, 300, 131, 31))
        self.salary.setObjectName("salary")
        self.label_9 = QtWidgets.QLabel(ModifyEmployee)
        self.label_9.setGeometry(QtCore.QRect(430, 280, 111, 16))
        self.label_9.setObjectName("label_9")
        self.label_9.setVisible(False)   # ??
        self.supssn = QtWidgets.QTextEdit(ModifyEmployee)
        self.supssn.setGeometry(QtCore.QRect(430, 300, 131, 31))
        self.supssn.setObjectName("supssn")
        self.supssn.setVisible(False)
        
        #self.deptname = QtWidgets.QTextEdit(ModifyEmployee)
        #self.deptname.setGeometry(QtCore.QRect(220, 380, 171, 31))
        #self.deptname.setObjectName("deptname")
        
        self.deptname = QtWidgets.QComboBox(ModifyEmployee)
        self.deptname.setGeometry(QtCore.QRect(220, 380, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.deptname.setSizePolicy(sizePolicy)
        #self.deptname.setEditable(False)
        self.deptname.setCurrentText("")
        self.deptname.setObjectName("deptname")
        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()

        cursor.execute("select concat(s.dnumber, ':', s.dname) dName  from department s order by dname")
        for row in cursor:
            self.deptname.addItem(row[0])
            # print(row[0])

        
        self.label_10 = QtWidgets.QLabel(ModifyEmployee)
        self.label_10.setGeometry(QtCore.QRect(70, 360, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_10.setVisible(False)   #
        self.label_11 = QtWidgets.QLabel(ModifyEmployee)
        self.label_11.setGeometry(QtCore.QRect(220, 360, 131, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(ModifyEmployee)
        self.label_12.setGeometry(QtCore.QRect(430, 360, 131, 16))
        self.label_12.setObjectName("label_12")
        self.deptno = QtWidgets.QTextEdit(ModifyEmployee)
        self.deptno.setGeometry(QtCore.QRect(70, 380, 81, 31))
        self.deptno.setObjectName("deptno")
        self.deptno.setVisible(False)

        #self.supervisorname = QtWidgets.QTextEdit(ModifyEmployee)
        #self.supervisorname.setGeometry(QtCore.QRect(430, 380, 171, 31))
        self.supervisorname = QtWidgets.QComboBox(ModifyEmployee)
        self.supervisorname.setGeometry(QtCore.QRect(430, 380, 180, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.sex.sizePolicy().hasHeightForWidth())
        self.supervisorname.setSizePolicy(sizePolicy)
        #self.supervisorname.setEditable(False)
        self.supervisorname.setCurrentText("")
        self.supervisorname.setObjectName("supervisorname")
        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()
        
        cursor.execute("select concat(s.ssn, ':', s.fname, ' ', s.minit, ' ', s.lname) ssnName  from employee s order by lname")
        for row in cursor:
            self.supervisorname.addItem(row[0])
            # print(row[0])

        self.gobutton = QtWidgets.QPushButton(ModifyEmployee)
        self.gobutton.setGeometry(QtCore.QRect(70, 440, 93, 28))
        self.gobutton.setObjectName("gobutton")

        self.retranslateUi(ModifyEmployee)
        self.buttonBox.rejected.connect(self.reject)
        self.gobutton.clicked.connect(self.processupdate)
        QtCore.QMetaObject.connectSlotsByName(ModifyEmployee)

        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()

        QApplication.setOverrideCursor(Qt.WaitCursor)
        # The select reads the employee details from the ssn provided
        cursor.execute("select a.*, b.dname, concat(s.fname, ' ', s.minit, ' ', s.lname) sname " + " from employee a, department b, employee s where a.ssn = "+
           self.passedssn + " and a.dno = b.dnumber and a.super_ssn = s.ssn for update of a")
        QApplication.restoreOverrideCursor()

        # iterate over result
        for row in cursor:
            #print(row)
            self.firstname.setText(row[0])
            self.middleinitial.setText(row[1])
            self.lastname.setText(row[2])
            self.empssn.setText(row[3])
            self.dateofbirth.setDate(row[4])
            self.address.setText(row[5])
            index = self.sex.findText(row[6], QtCore.Qt.MatchFixedString)
            if index >= 0:
                self.sex.setCurrentIndex(index)
            self.salary.setText(str(row[7]))
            self.supssn.setText(str(row[8]))
            self.deptno.setText(str(row[9]))
            #self.deptname.setText(row[10])
            #self.supervisorname.setText(row[11])
            index = self.deptname.findText(str(row[9])+':'+str(row[10]), QtCore.Qt.MatchFixedString)
            if index >= 0:
                self.deptname.setCurrentIndex(index)
            index = self.supervisorname.findText(str(row[8])+':'+str(row[11]), QtCore.Qt.MatchFixedString)
            if index >= 0:
                self.supervisorname.setCurrentIndex(index)

 
        cursor.close()
        db.close()

    def retranslateUi(self, ModifyEmployee):
        _translate = QtCore.QCoreApplication.translate
        ModifyEmployee.setWindowTitle(_translate("ModifyEmployee", "Employee Details"))
        self.label.setText(_translate("ModifyEmployee", "First Name"))
        self.label_2.setText(_translate("ModifyEmployee", "Last Name"))
        self.label_3.setText(_translate("ModifyEmployee", "M.I."))
        self.label_4.setText(_translate("ModifyEmployee", "SSN"))
        self.label_5.setText(_translate("ModifyEmployee", "Date of Birth"))
        self.label_6.setText(_translate("ModifyEmployee", "Address"))
        self.label_7.setText(_translate("ModifyEmployee", "Sex"))
        self.label_8.setText(_translate("ModifyEmployee", "Salary"))
        self.label_9.setText(_translate("ModifyEmployee", "Supervisor SSN"))
        self.label_10.setText(_translate("ModifyEmployee", "Dept No"))
        self.label_11.setText(_translate("ModifyEmployee", "Department Name"))
        self.label_12.setText(_translate("ModifyEmployee", "Supervisor Name"))
        self.gobutton.setText(_translate("MainWindow", "Go"))

    def processupdate(self):
        print("update proc")
        db = mysql.connector.connect(option_files='mydb.conf')
        cursor = db.cursor()
        fname = self.firstname.toPlainText()
        minit = self.middleinitial.toPlainText()+''
        lname = self.lastname.toPlainText()
        essn = self.empssn.toPlainText()
        dob = self.dateofbirth.date()
        #print(dob.getDate())
        # These are the values that can be edited or maintained for the updating process (above values
        # cannot be changed in the update process)
        addr = self.address.toPlainText()
        sx = self.sex.currentText()
        sal=self.salary.toPlainText()
        dname = self.deptname.currentText()
        dno = dname[0:dname.index(':')]
        dname = dname[dname.index(':')+1:]
        #print(dno, dname)
        supname = self.supervisorname.currentText()
        spssn = supname[0:supname.index(':')]
        supname = supname[supname.index(':')+1:]
        #print(dno, dname)
        val = (addr, sx, sal, spssn, dno, essn)
        sql = "update employee SET address=%s, sex=%s, salary=%s, super_ssn=%s, dno=%s WHERE ssn=%s" 
        cursor.close()
        cursor = db.cursor()
        QApplication.setOverrideCursor(Qt.WaitCursor)
        cursor.execute(sql, val)
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Employee "+ str(lname) + " updated")
        msg.setWindowTitle("Modify Employee")
        msg.exec()
        db.commit()
        QApplication.restoreOverrideCursor()
        db.close()
  
    def reject(self):
        print("reject")  # test
        self.ModDep.close()
 

 

