# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removedependent.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QTableWidgetItem
import mysql.connector
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator


class Ui_RemoveDependent(object):
    passedssn = -1
    deldepname = ""
    db = None # mysql connection

    def __init__(self, obj):
        self.passedssn = obj.textEdit.text()

    def setupUi(self, RemoveDependent):
        RemoveDependent.setObjectName("RemoveDependent")
        RemoveDependent.resize(700, 505)
        self.buttonBox = QtWidgets.QDialogButtonBox(RemoveDependent)
        self.buttonBox.setGeometry(QtCore.QRect(310, 420, 321, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(RemoveDependent)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 80, 641, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabdependents = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabdependents.sizePolicy().hasHeightForWidth())
        self.tabdependents.setSizePolicy(sizePolicy)
        self.tabdependents.setMinimumSize(QtCore.QSize(639, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabdependents.setFont(font)
        self.tabdependents.setAutoFillBackground(True)
        self.tabdependents.setGridStyle(QtCore.Qt.SolidLine)
        self.tabdependents.setRowCount(10)
        self.tabdependents.setColumnCount(4)
        self.tabdependents.setObjectName("tabdependents")
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabdependents.setHorizontalHeaderItem(3, item)
        self.tabdependents.horizontalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tabdependents)
        self.label_2 = QtWidgets.QLabel(RemoveDependent)
        self.label_2.setGeometry(QtCore.QRect(30, 360, 161, 16))
        self.label_2.setObjectName("label_2")
        self.empssn = QtWidgets.QLineEdit(RemoveDependent)
        self.empssn.setGeometry(QtCore.QRect(90, 20, 101, 31))
        self.empssn.setObjectName("empssn")
        self.gobutton = QtWidgets.QPushButton(RemoveDependent)
        self.gobutton.setGeometry(QtCore.QRect(40, 420, 93, 28))
        self.gobutton.setObjectName("gobutton")
        self.dname = QtWidgets.QTextEdit(RemoveDependent)
        self.dname.setGeometry(QtCore.QRect(230, 350, 271, 31))
        self.dname.setObjectName("dname")
        self.label = QtWidgets.QLabel(RemoveDependent)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.label.setObjectName("label")
        self.empname = QtWidgets.QLabel(RemoveDependent)
        self.empname.setGeometry(QtCore.QRect(240, 20, 71, 21))
        self.empname.setObjectName("empname")
        self.empname_2 = QtWidgets.QTextEdit(RemoveDependent)
        self.empname_2.setGeometry(QtCore.QRect(310, 20, 261, 31))
        self.empname_2.setObjectName("empname_2")
        self.label_6 = QtWidgets.QLabel(RemoveDependent)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 121, 16))
        self.label_6.setObjectName("label_6")
        self.depcount = QtWidgets.QTextEdit(RemoveDependent)
        self.depcount.setGeometry(QtCore.QRect(210, 300, 31, 31))
        self.depcount.setObjectName("depcount")

        self.retranslateUi(RemoveDependent)
        self.buttonBox.rejected.connect(RemoveDependent.reject)
        QtCore.QMetaObject.connectSlotsByName(RemoveDependent)

        self.empssn.setText(self.passedssn)
        self.empssn.setDisabled(True)
        self.select_data()
        self.tabdependents.clicked.connect(self.select_depname)

        self.gobutton.clicked.connect(self.processdelete)

    def retranslateUi(self, RemoveDependent):
        _translate = QtCore.QCoreApplication.translate
        RemoveDependent.setWindowTitle(_translate("RemoveDependent", "RemoveDependent"))
        self.tabdependents.setSortingEnabled(True)
        item = self.tabdependents.horizontalHeaderItem(0)
        item.setText(_translate("RemoveDependent", "Name"))
        item = self.tabdependents.horizontalHeaderItem(1)
        item.setText(_translate("RemoveDependent", "Sex"))
        item = self.tabdependents.horizontalHeaderItem(2)
        item.setText(_translate("RemoveDependent", "Date of Birth"))
        item = self.tabdependents.horizontalHeaderItem(3)
        item.setText(_translate("RemoveDependent", "Relationship"))
        self.label_2.setText(_translate("RemoveDependent", "Name to Delete:"))
        self.gobutton.setText(_translate("RemoveDependent", "Delete"))
        self.label.setText(_translate("RemoveDependent", "Emp SSN"))
        self.empname.setText(_translate("RemoveDependent", "Emp Name"))
        self.label_6.setText(_translate("RemoveDependent", "Dependent Count"))

    def select_data(self):
        # Retrieve data on existing dependents that correspond to an ssn value given
        try:
            #print("select dependents")
            self.db = mysql.connector.connect(option_files='mydb.conf')
            cursor = self.db.cursor()
            cursor.execute("select concat(fname, ' ', minit,' ', lname) empname from employee where ssn =" + str(self.passedssn) +
               " for update ")
            for row in cursor:
                self.empname_2.setText(row[0])
                #print(row)
            self.empname_2.setDisabled(True)
            nrows = cursor.rowcount
            #print('nrows', nrows)
            if nrows <= 0 :
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QMessageBox.Information)
                msg.setText("No employee with ssn "+ str(self.passedssn))
                msg.setWindowTitle("Add Dependent")
                msg.exec()
                self.reject()

            cursor.execute("select dependent_name, sex, bdate, relationship from dependent where essn =" + str(self.passedssn) +
              " for update ")
            result = cursor.fetchall()
            nrows = cursor.rowcount
            self.depcount.setText(str(nrows))
            self.depcount.setDisabled(True)
            self.tabdependents.setRowCount(0)
            for rnum, rdata in enumerate(result):
                self.tabdependents.insertRow(rnum)
                for colnum, cdata in enumerate(rdata):
                    self.tabdependents.setItem(rnum, colnum,QTableWidgetItem(str(cdata)))
            #self.tabdependents.setDisabled(True)
        except mysql.connector.Error as e:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("SQL Error "+ str(e.msg))
            msg.setWindowTitle("Add Dependent")
            msg.exec()

    def select_depname(self, item):
        cellContent = item.data()
        #print(cellContent)  # test
        #sf = "You clicked on {} {}".format(item.row(), item.column())
        #print(sf)
        myrow = item.row()
        mycol = item.column()
        if mycol == 0:
            self.dname.setText(cellContent)
            self.deldepname = cellContent
            
    def processdelete(self, item):
        if self.dname != "":
            self.db = mysql.connector.connect(option_files='mydb.conf')
            cursor = self.db.cursor()
            # The number of variables we pass to the delete query is small enough where we can place them directly into
            # the string that forms the sql query
            cursor.execute("delete from dependent where essn =" + str(self.passedssn)+" and dependent_name = '"+self.deldepname+"'")
            self.db.commit()
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setText("Deleted dependent with essn "+ str(self.passedssn) + " dep name '" + self.deldepname +"'")
            msg.setWindowTitle("Delete Dependent")
            msg.exec()
            self.dname.setText("")
            self.select_data()

    def reject(self):
        #print("in reject")
        self.db.commit()
        self._close()
        QDialog.reject(self)

 